[package]
name = "rust_game_proto"
version = "0.1.0"
authors = ["Adam Bates <adam@adambates.ca>"]
edition = "2018"

[dependencies]
ggez = "~0.5.1"

# set compile-time log level to warn in release, and debug in debug
log = { version = "~0.4.11", features = ["max_level_debug", "release_max_level_warn"] }
